### ISSUE TITLE
Doesn't work for Twitter?

### ISSUE THREAD

**Issue by neopostmodern** [raicem/impulse-blocker#33] opened 2019-01-16 10:26 UTC
It's pretty weird. For some domains I've blocked it works perfectly fine, all of the time.
But for Twitter it works close to never. See these fine screenshots:

![screenshot from 2019-01-16 11-13-12 impulse blocker - twitter](https://user-images.githubusercontent.com/786840/51242510-6c993900-1980-11e9-8168-fe335a2e085a.png)

...which shows it clearly recognizes it _should_ block the site, but doesn't.
My filters are alright I think?

![screenshot from 2019-01-16 11-13-23 impulse blocker - block list](https://user-images.githubusercontent.com/786840/51242519-715ded00-1980-11e9-8944-4e5d718d60f0.png)

**But** the weirdness doesn't stop here. If I search for "twitter" on Startpage and click the link to Twitter, it'll load the page. If I search for "twitter isotrumpp" and click [the link](https://twitter.com/isotrumpp?lang=en) it *will* block.

![screenshot from 2019-01-16 11-24-21 impulse blocker - twitter blocked](https://user-images.githubusercontent.com/786840/51242918-77a09900-1981-11e9-8038-243121aae2ad.png)

 Weirdness.

**Comment by raicem** [comment] 2019-01-16 11:35
Huh. You are the second person to report twitter.com not being blocked. I've looked into it. But couldn't figure why could that be and ignored the problem afterwards. Cause I tried many scenerios but could not replicate it. I currently block twitter.com successfully with no problems. But it is obvious that I should look into it more deeply.

About the CSP. Yeah, that may well be. It'a good place to start debugging.But honestly, I am not injecting anyting into the webpages. All the blocking is done via the Webextension API. So twitter.com probably does not even know that my extension exists on the browser. 

Many thanks for reporting. 

I am now working on a big rewrite for the extension. Hopefully I can figure out why.

**Comment by raicem** [comment] 2019-02-18 13:43
I think I figured it out. Just ran into that issue myself. I believe it is because twitter.com registering a service worker. When I visit twitter.com it loads the inital html from the cached version and only sending request to api.twitter.com. It is obviously not blocked. If I do hard refresh (ctrl + shift + r) it is blocked. If i delete service worker manaully it is blocked. So that is a nice problem to have 😅

**Comment by jeremydouglas** [comment] 2019-07-11 12:42
Thanks for the tip on this. Blocking api.twitter.com as well seems to help. It's then more work to turn it back on, as there's to urls to turn on. But, maybe that's a good thing.

**Comment by raicem** [comment] 2019-07-11 12:54
They way we are blocking the websites are very low level. We just look at the outgoing HTTP requests based on patterns. Other blockers generally wait for tabs to be loaded. That's why in some of them you can see flash of content of the website and then the blocker interferes. 

I think eventually we'll have to implement it that way. Otherwise we miss the websites with service workers. (Unless Firefox implements a magical way of telling us that it loads twitter.com using service worker cache). 

So I'll keep this issue open to nag me.

**Comment by peeter-t2** [comment] 2019-08-01 17:53
+1 
api.twitter.com doesn't seem to help either, at least after the redesign of the site. Rest is great tho!

**Comment by niazarak** [comment] 2019-08-12 20:44
I don't know what kind of a thing is a service worker, but unregistering it for twitter in firefox seems to fix the problem (go to `about:debugging#workers` and click `unregister` for `twitter.com/sw.js`). 

Of course, unless you unblock twitter so the service worker is registered again, it seems.

Yet another reason not to visit twitter, I guess.

**Comment by peeter-t2** [comment] 2019-08-13 08:39
Yep @niazarak , this works until the next peek into twitter with the blocker off. So indeed, more of a reason for self-discipline.

**Comment by Waquo** [comment] 2019-09-09 21:16
I have the same issue and can confirm it is caused by twitter's service worker. Unregistering it fixes the problem temporarily, blocking https://twitter.com/sw.js seems to work permanently.

The cost of this is of course that you have to have something like uBlock Origin installed and have to know how to use it, and that you forgo the performance benefits of service worker caching on the affected sites, so adjusting the impulse blocker to handle service workers would be ideal.

**Comment by TroyFletcher** [comment] 2019-11-13 15:51
Also having this issue, blocking twitter.com/sw.js and api.twitter.com makes no difference, only the hard refresh causes it to register and block.

**Comment by scaredyghost** [comment] 2019-12-04 21:29
Just coming in to say that I'm also having problems getting Twitter to block. Like TroyFletcher, I've added twitter.com/sw.js and api.twitter.com to my blacklist, but neither has solved the problem. Hard-refreshing works... but that kind of defeats the purpose of having an automatic site blocker.

I'm particularly disappointed because Twitter is my biggest distraction. Of all the rotten luck! Hopefully it gets figured out soon. :(

**Comment by raicem** [comment] 2020-06-30 11:10
I am not having this error for a very long time and I can't even replicate it. Even with or without service workers twitter.com gets blocked on my Firefox 77 installation. I think Firefox implemented a fix under the hood. I have checked the extension API changelogs but couldn't see it being mentioned. 

I'll close this issue after a while.

**Comment by Waquo** [comment] 2020-06-30 15:37
I can no longer replicate the error either.

**Closed** 2020-07-06 06:56 UTC
Labels: bug

**Comment by elvey** [comment] 2020-12-23 19:45
@raicem Since this is closed, consider updating your review reply to say so. The one at https://addons.mozilla.org/en-US/firefox/addon/impulse-blocker/reviews/1408018/?utm_content=discopane-entry-link&utm_medium=firefox-browser&utm_source=firefox-browser :-)
